name: Request resource access

# See the json schema to help you create / update this form
# https://json.schemastore.org/github-issue-forms.json

description: Fill in this template to ask for specific resources

labels: ["resource_request :heavy_dollar_sign:"]

# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        ## Guidelines

        Fill in this template to ask for specific resources for a new project or extend those of already existing project.

  - type: markdown
    attributes:
      value: |
        ## Project info

  - type: textarea
    attributes:
      label: Title
      description: Add a title to describe your project.
    validations:
      required: true

  - type: dropdown
    attributes:
      multiple: false
      label: Is this a new project?
      options:
        - "yes"
        - "no"

  - type: textarea
    attributes:
      label: People involved
      description: Add the full name of the people involved in the project with Github IDs and email address.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Project Description
      description: Add a brief description of the project.
      value: |
        - What are you doing, for whom, and why?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Link to project repository/sources
      description:
        "If your project already exists, please provide a link to project
        repository/sources (e.g., Github link)"
      value: https://github.com/user_name/my_awesome_project
    validations:
      required: false

  - type: dropdown
    attributes:
      label: What resources do you require?
      multiple: true
      options:
        - Virtual Machines
        - Object Storage
        - GPU resources
        - HPC
        - other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description:
        Ticked the `other` option on one of the menu above and want to add
        details? Please use the space if there is anything else that you would
        like to add about your project.
    validations:
      required: false
